name: LightningDeath
api: 5.3.0
authors:
  - provsalt
  - muqsit
version: 1.3.6
src-namespace-prefix: provsalt\lightningdeath
website: rayisa.dev
main: provsalt\lightningdeath\Loader
permissions:
 lightningdeath.bypass:
    default: false
